//! Exact-in quote that reproduces the contract's `instructions/user/swap.rs`.
//!
//! GENERATED by the port script (see README) — the segments between the
//! `── handler lines …` banners are copied verbatim from `swap::handler`, and
//! `tests/coffer_source_parity.rs` asserts they still match the contract.
//! Do not rustfmt this file (the `coffer` module is `#[rustfmt::skip]`).
//!
//! `calculate_swap_fee` / `calculate_protocol_fee` are the handler's private
//! helpers, copied verbatim. [`quote_exact_in`] is the handler with the account
//! plumbing and CPIs removed: every guard, the fee split, the curve call, the
//! 4-segment surge-fee loop and the post-surge payout are the handler's own
//! lines; the balance updates the handler performs afterwards are re-run as
//! overflow CHECKS so a quote fails on exactly the inputs the program rejects.
//!
//! The ONE deliberate deviation: the handler runs `check_and_advance` on
//! `&mut pool.tokens[token_in_idx].dynamics`; a quote must not mutate the
//! venue, so it runs on a stack copy of that row (`dynamics_in`). The copy is
//! returned in [`SwapOutcome`] and [`apply_swap`] commits it, which is how the
//! fixture tests predict the post-swap account and compare it byte for byte
//! with what the program wrote.

use crate::coffer::errors::ErrorCode;
use crate::coffer::math::CofferMath;
use crate::coffer::math::max_selloff::MaxSelloffResult;
use crate::coffer::prelude::*;
use crate::coffer::state::{AssetDynamics, CofferPool};

/// Everything `swap::handler` computes before it moves tokens.
#[derive(Debug, Clone, Copy)]
pub struct SwapOutcome {
    /// LP swap fee, ceil-rounded, in input atoms.
    pub fee_amount: u64,
    /// Protocol share of `fee_amount`, ceil-rounded.
    pub protocol_fee_amount: u64,
    /// `amount_in - fee_amount`: what the curve is fed.
    pub amount_in_after_fee: u64,
    /// `amount_in - protocol_fee_amount`: what the pool's balances gain.
    pub amount_in_after_protocol_fees: u64,
    /// Gross curve output (what leaves the trading reserves).
    pub amount_out: u64,
    /// Variable sell-off surge fee carved out of `amount_out`.
    pub surge_fee_amount: u64,
    /// `amount_out - surge_fee_amount`: what the user receives.
    pub amount_out_user: u64,
    /// The sliding-window result when the input token has a cap configured.
    pub max_selloff_result: Option<MaxSelloffResult>,
    /// The input token's dynamics row AFTER `check_and_advance` (window
    /// rotation, snapshot capture, carry-over rescale), BEFORE the balance
    /// update. Commit it with [`apply_swap`].
    pub dynamics_in: AssetDynamics,
}

/// The quote. Mirrors `swap::handler` up to (not including) the CPIs. `now`
/// is `Clock::unix_timestamp`; the decimals are read off the mints by the
/// venue (the curve ignores them, the handler passes them through).
///
/// # Errors
/// Exactly the handler's: `PoolDisabled`, `SwapsDisabled`, `ZeroAmount`,
/// `InvalidTokenIndex`, `TokenInactive`, `MaxSelloffInvalidConfig`,
/// `MaxSelloffExceeded`, `ZeroFeeAmount`, `MathOverflow` / `MathUnderflow`,
/// `AmountOutExceedsBalance`, `InsufficientLiquidity`.
#[allow(clippy::too_many_arguments)]
pub fn quote_exact_in(
    pool: &CofferPool,
    amount_in: u64,
    token_in_index: u8,
    token_out_index: u8,
    decimals_in: u8,
    decimals_out: u8,
    now: i64,
) -> Result<SwapOutcome> {
    // ── handler lines 102-125 (guards) ───────────────────────────────────
    require!(pool.pool_enabled, ErrorCode::PoolDisabled);
    require!(pool.swaps_enabled, ErrorCode::SwapsDisabled);
    require!(amount_in > 0, ErrorCode::ZeroAmount);

    require!(
        (token_in_index as usize) < pool.token_count as usize,
        ErrorCode::InvalidTokenIndex
    );
    require!(
        (token_out_index as usize) < pool.token_count as usize,
        ErrorCode::InvalidTokenIndex
    );
    require!(token_in_index != token_out_index, ErrorCode::InvalidTokenIndex);

    let token_in_idx = token_in_index as usize;
    let token_out_idx = token_out_index as usize;

    // Per-token input kill switch: a deactivated token cannot be sold INTO
    // the pool (it can still be bought as the output side). Used to stop
    // accepting a compromised token without pausing the whole pool.
    require!(
        pool.tokens[token_in_idx].config.is_active,
        ErrorCode::TokenInactive
    );

    // (mint / token-program / vault account checks are structural — the
    // instruction builder derives those accounts from the same pool state.)

    // ── handler lines 151-168, on a COPY of the input token's dynamics ──
    let virtual_balance_in = pool.tokens[token_in_idx].dynamics.virtual_balance;
    let max_selloff_pct = pool.tokens[token_in_idx].config.max_selloff_pct as u64;
    let max_selloff_period = pool.tokens[token_in_idx].config.max_selloff_period_length;
    let mut dynamics_in = pool.tokens[token_in_idx].dynamics;
    let max_selloff_result = crate::coffer::math::max_selloff::check_and_advance(
        &mut dynamics_in,
        max_selloff_pct,
        max_selloff_period,
        amount_in,
        virtual_balance_in,
        now,
    )?;

    // ── handler lines 173-199 (fee split + curve) ────────────────────────
    let virtual_balance_out = pool.tokens[token_out_idx].dynamics.virtual_balance;
    let actual_balance_out = pool.tokens[token_out_idx].dynamics.actual_balance;
    let weight_in = pool.tokens[token_in_idx].config.normalized_weight;
    let weight_out = pool.tokens[token_out_idx].config.normalized_weight;

    let fee_amount = calculate_swap_fee(amount_in, pool.swap_fee_rate)?;
    require!(
        pool.swap_fee_rate == 0 || fee_amount > 0,
        ErrorCode::ZeroFeeAmount
    );
    let amount_in_after_fee = amount_in
        .checked_sub(fee_amount)
        .ok_or(ErrorCode::MathUnderflow)?;

    let protocol_fee_amount = calculate_protocol_fee(fee_amount, pool.protocol_fee_rate)?;
    let amount_in_after_protocol_fees = amount_in - protocol_fee_amount;

    let amount_out = CofferMath::calc_out_given_in(
        virtual_balance_in,
        weight_in,
        virtual_balance_out,
        weight_out,
        amount_in_after_fee,
        actual_balance_out,
        decimals_in,
        decimals_out,
    )?;

    // ── handler lines 201-330 (surge fee) ────────────────────────────────
    // ── Variable sell-off surge fee ──────────────────────────────────────
    // Charged on `amount_out` (the OUTPUT token leaving the pool) and routed
    // 100% to the protocol bucket of the output token — never to LPs (so an
    // attacker dumping a hacked token can't harvest the fee). Active only
    // when the input token's max-selloff window is enabled (we have a fill
    // result) AND a curve is configured. Convex-rising in window fill.
    let surge_fee_amount: u64 = if let Some(ref r) = max_selloff_result {
        let cfg = &pool.tokens[token_in_idx].config;
        let surge_pct = crate::coffer::math::surge_fee::calc_surge_fee_pct(
            r.effective_selloff_before,
            r.effective_selloff,
            r.max_selloff_cap,
            cfg.variable_fee_threshold_pct,
            cfg.variable_fee_slope_low_pct,
            cfg.variable_fee_slope_mid_pct,
            cfg.variable_fee_slope_high_pct,
            cfg.variable_fee_kink_pct,
        )?;
        if surge_pct == 0 {
            0
        } else {
            let pct_scale = crate::coffer::constants::PERCENT_SCALE as u128;

            // Charge only the output produced ABOVE the threshold, segment by
            // segment across the taxed span.
            //
            // The window advances in INPUT units while the fee is charged on
            // OUTPUT, and the AMM curve is concave, so a slice of window does
            // NOT correspond to a proportional slice of output. Applying one
            // average rate to the whole output therefore left M-05's dodge
            // partly open. Measured whole-vs-split spread before this change,
            // by weight ratio: 1.88x at 50/50, 6.4x at 80/20, 82x at 90/10,
            // and at 95/5 some partitions paid essentially nothing.
            //
            // Splitting the taxed span into `SURGE_FEE_SEGMENTS` pieces and
            // charging each piece's REAL output at that piece's average rate
            // brings the spread to 1.011 / 1.030 / 1.064 / 1.151 for the same
            // four ratios. Each segment costs one `calc_out_given_in`; the
            // final boundary is `amount_out`, already in hand.
            //
            // Conservative BY CONSTRUCTION, not by luck: within a segment the
            // rate rises while marginal output falls, so the two are negatively
            // correlated and Chebyshev's sum inequality gives
            // `mean(rate · dy) <= mean(rate) · mean(dy)`. The charge can only
            // exceed the exact output-weighted integral, never fall short.
            //
            // Note an output-denominated surge fee inherently loses its bite on
            // extremely lopsided pools (99/1): nearly all output is delivered
            // before the threshold, so there is almost nothing left to charge.
            // No choice of segment count changes that; only charging the fee on
            // the INPUT side would, at the cost of accruing the token being
            // dumped.
            let thr_units = (r.max_selloff_cap as u128)
                .checked_mul(cfg.variable_fee_threshold_pct as u128)
                .ok_or(ErrorCode::MathOverflow)?
                / pct_scale;
            let before = r.effective_selloff_before as u128;
            let after = r.effective_selloff as u128;
            let span = after.saturating_sub(before);
            let taxed_lo = core::cmp::max(before, thr_units);

            if span == 0 || after <= taxed_lo {
                0
            } else {
                let segments = crate::coffer::constants::SURGE_FEE_SEGMENTS as u128;
                // Cumulative curve output at window position `u`. Flooring the
                // input understates the output, which overstates the taxed
                // remainder — the safe direction.
                let cumulative_out = |u: u128| -> Result<u64> {
                    if u <= before {
                        return Ok(0);
                    }
                    if u >= after {
                        return Ok(amount_out);
                    }
                    let x = (amount_in_after_fee as u128)
                        .checked_mul(u - before)
                        .ok_or(ErrorCode::MathOverflow)?
                        / span;
                    CofferMath::calc_out_given_in(
                        virtual_balance_in,
                        weight_in,
                        virtual_balance_out,
                        weight_out,
                        x as u64,
                        actual_balance_out,
                        decimals_in,
                        decimals_out,
                    )
                };

                let taxed_width = after - taxed_lo;
                let mut fee_acc: u128 = 0;
                let mut prev_u = taxed_lo;
                let mut prev_y = cumulative_out(taxed_lo)?;
                for k in 1..=segments {
                    let u = if k == segments {
                        after
                    } else {
                        taxed_lo + taxed_width * k / segments
                    };
                    let y = cumulative_out(u)?;
                    let seg_out = y.saturating_sub(prev_y) as u128;
                    if seg_out > 0 && u > prev_u {
                        let seg_pct = crate::coffer::math::surge_fee::calc_surge_fee_pct(
                            prev_u as u64,
                            u as u64,
                            r.max_selloff_cap,
                            cfg.variable_fee_threshold_pct,
                            cfg.variable_fee_slope_low_pct,
                            cfg.variable_fee_slope_mid_pct,
                            cfg.variable_fee_slope_high_pct,
                            cfg.variable_fee_kink_pct,
                        )? as u128;
                        let num = seg_out
                            .checked_mul(seg_pct)
                            .ok_or(ErrorCode::MathOverflow)?;
                        fee_acc = fee_acc
                            .checked_add(num / pct_scale + if num % pct_scale != 0 { 1 } else { 0 })
                            .ok_or(ErrorCode::MathOverflow)?;
                    }
                    prev_u = u;
                    prev_y = y;
                }
                fee_acc.min(amount_out as u128) as u64
            }
        }
    } else {
        0
    };

    // ── handler lines 332-349 (payout; the slippage check is the caller's) ─
    // User receives the curve output minus the surge fee.
    let amount_out_user = amount_out
        .checked_sub(surge_fee_amount)
        .ok_or(ErrorCode::MathUnderflow)?;

    require!(amount_out <= actual_balance_out, ErrorCode::InsufficientLiquidity);

    // ── handler lines 351-374, as CHECKS ─────────────────────────────────
    // The handler's balance / fee-bucket updates use checked arithmetic and
    // revert the swap on overflow. A quote must fail on the same inputs, so
    // the same operations run here on the same operands, results discarded.
    virtual_balance_in
        .checked_add(amount_in_after_protocol_fees)
        .ok_or(ErrorCode::MathOverflow)?;
    virtual_balance_out
        .checked_sub(amount_out)
        .ok_or(ErrorCode::MathUnderflow)?;
    pool.tokens[token_in_idx]
        .dynamics
        .actual_balance
        .checked_add(amount_in_after_protocol_fees)
        .ok_or(ErrorCode::MathOverflow)?;
    pool.tokens[token_out_idx]
        .dynamics
        .actual_balance
        .checked_sub(amount_out)
        .ok_or(ErrorCode::MathUnderflow)?;
    pool.tokens[token_in_idx]
        .dynamics
        .protocol_fees_owed
        .checked_add(protocol_fee_amount)
        .ok_or(ErrorCode::MathOverflow)?;
    pool.tokens[token_out_idx]
        .dynamics
        .protocol_fees_owed
        .checked_add(surge_fee_amount)
        .ok_or(ErrorCode::MathOverflow)?;

    Ok(SwapOutcome {
        fee_amount,
        protocol_fee_amount,
        amount_in_after_fee,
        amount_in_after_protocol_fees,
        amount_out,
        surge_fee_amount,
        amount_out_user,
        max_selloff_result,
        dynamics_in,
    })
}

/// Commit a [`SwapOutcome`] to `pool` exactly as the handler does (lines
/// 351-374): the window state from `check_and_advance`, then the balance and
/// protocol-fee updates. Lets a caller predict the post-swap account.
pub fn apply_swap(
    pool: &mut CofferPool,
    token_in_index: u8,
    token_out_index: u8,
    outcome: &SwapOutcome,
) -> Result<()> {
    let token_in_idx = token_in_index as usize;
    let token_out_idx = token_out_index as usize;
    require!(token_in_idx < pool.token_count as usize, ErrorCode::InvalidTokenIndex);
    require!(token_out_idx < pool.token_count as usize, ErrorCode::InvalidTokenIndex);
    require!(token_in_idx != token_out_idx, ErrorCode::InvalidTokenIndex);

    let virtual_balance_in = pool.tokens[token_in_idx].dynamics.virtual_balance;
    let virtual_balance_out = pool.tokens[token_out_idx].dynamics.virtual_balance;
    let amount_in_after_protocol_fees = outcome.amount_in_after_protocol_fees;
    let amount_out = outcome.amount_out;
    let protocol_fee_amount = outcome.protocol_fee_amount;
    let surge_fee_amount = outcome.surge_fee_amount;

    // `check_and_advance` mutated the row in place on-chain.
    pool.tokens[token_in_idx].dynamics = outcome.dynamics_in;

    // ── handler lines 351-374 ────────────────────────────────────────────
    pool.tokens[token_in_idx].dynamics.virtual_balance = virtual_balance_in
        .checked_add(amount_in_after_protocol_fees)
        .ok_or(ErrorCode::MathOverflow)?;

    // The invariant moves by the GROSS curve output (`amount_out`): that's
    // what left the trading reserves. The surge fee is carved out of the
    // output that already left the curve and re-credited to the protocol
    // bucket (vault = actual_balance + protocol_fees_owed stays consistent).
    pool.tokens[token_out_idx].dynamics.virtual_balance = virtual_balance_out
        .checked_sub(amount_out)
        .ok_or(ErrorCode::MathUnderflow)?;

    pool.tokens[token_in_idx].dynamics.actual_balance = pool.tokens[token_in_idx].dynamics.actual_balance
        .checked_add(amount_in_after_protocol_fees)
        .ok_or(ErrorCode::MathOverflow)?;

    pool.tokens[token_out_idx].dynamics.actual_balance = pool.tokens[token_out_idx].dynamics.actual_balance
        .checked_sub(amount_out)
        .ok_or(ErrorCode::MathUnderflow)?;

    pool.add_protocol_fees(token_in_idx, protocol_fee_amount)?;
    if surge_fee_amount > 0 {
        pool.add_protocol_fees(token_out_idx, surge_fee_amount)?;
    }
    Ok(())
}

/// `fee = amount * swap_fee_rate / SWAP_FEE_PRECISION`. The cast is a
/// checked `try_into` to drop silent truncation.
///
/// # Parameters
/// * `amount`   — input amount (raw units).
/// * `fee_rate` — `pool.swap_fee_rate` (hundredths of bps).
///
/// # Returns
/// Fee in raw units of the input token.
///
/// # Used by
/// `swap::handler`.
pub fn calculate_swap_fee(amount: u64, fee_rate: u32) -> Result<u64> {
    // CEILING, not floor. H-01 fixed this rounding for the protocol's share of
    // the fee but left the base fee itself rounding down — the same defect one
    // level up. Flooring hands the caller the fractional part on every swap,
    // and splitting a trade multiplies the giveaway: at 0.1%, one swap of
    // 3_998 owes 3.998 and was charged 3, while two swaps of 1_999 owe the
    // same 3.998 in total and were charged 1 + 1 = 2.
    //
    // For 6- and 9-decimal tokens that is dust. For a 0-decimal token of any
    // value it is a whole token per call, and nothing bounds how many calls a
    // transaction may make. `ZeroFeeAmount` only ever caught a fee that
    // rounded to zero, never a fee that rounded down by one.
    let scale = crate::coffer::constants::SWAP_FEE_PRECISION as u128;
    let num = (amount as u128)
        .checked_mul(fee_rate as u128)
        .ok_or(ErrorCode::MathOverflow)?;
    let fee = num / scale + if num % scale != 0 { 1 } else { 0 };

    fee.try_into().map_err(|_| ErrorCode::MathOverflow.into())
}

/// `protocol_fee = swap_fee * protocol_fee_rate / PROTOCOL_FEE_PRECISION`.
/// Same checked-cast story as `calculate_swap_fee`.
///
/// # Parameters
/// * `swap_fee`         — output of `calculate_swap_fee`.
/// * `protocol_fee_rate`— `pool.protocol_fee_rate` (basis points).
///
/// # Used by
/// `swap::handler`.
pub fn calculate_protocol_fee(swap_fee: u64, protocol_fee_rate: u16) -> Result<u64> {
    let scale = crate::coffer::constants::PROTOCOL_FEE_PRECISION as u128;
    let num = (swap_fee as u128)
        .checked_mul(protocol_fee_rate as u128)
        .ok_or(ErrorCode::MathOverflow)?;

    // Rounded UP. Flooring here meant the protocol was paid nothing whenever
    // `swap_fee * rate < PROTOCOL_FEE_PRECISION` — at the default 20% that is
    // every swap whose LP fee is 4 raw units or less, and the whole fee went
    // to LPs instead. `swap` already rejects a swap fee that rounds to zero
    // (`ZeroFeeAmount`), so the protocol's cut is the only place where a
    // charged fee could still resolve to nothing; grinding dust swaps turned
    // that into a systematic revenue leak.
    //
    // Ceiling can only ever add one raw unit, and since
    // `protocol_fee_rate <= MAX_PROTOCOL_FEE_RATE` (50%) the result stays
    // strictly below `swap_fee`, so the LP share never goes negative.
    let protocol_fee = num / scale + if num % scale != 0 { 1 } else { 0 };

    protocol_fee.try_into().map_err(|_| ErrorCode::MathOverflow.into())
}

/// Largest gross `amount_in` the input token's sell-off window still admits
/// at `now`, or `None` when the token has no cap. Mirrors the arithmetic of
/// `check_and_advance` (rotation, snapshot, carry-over rescale) without
/// committing anything: `cap - effective_before`, floored at zero.
///
/// Since the window advances by the GROSS amount, this is exactly the
/// boundary: `quote_exact_in(headroom)` passes the cap check and
/// `quote_exact_in(headroom + 1)` fails it with `MaxSelloffExceeded`.
pub fn selloff_headroom(pool: &CofferPool, token_in_index: u8, now: i64) -> Result<Option<u64>> {
    let idx = token_in_index as usize;
    require!(idx < pool.token_count as usize, ErrorCode::InvalidTokenIndex);
    let cfg = &pool.tokens[idx].config;
    if cfg.max_selloff_pct == 0 {
        return Ok(None);
    }
    // A zero-amount probe runs the full window arithmetic and reports the
    // fill BEFORE any amount is added. It can still fail with
    // `MaxSelloffExceeded` when the carry-over alone already exceeds the cap
    // (a cap tightened mid-window), in which case the headroom is zero.
    let mut dynamics = pool.tokens[idx].dynamics;
    let virtual_balance = dynamics.virtual_balance;
    let probe = crate::coffer::math::max_selloff::check_and_advance(
        &mut dynamics,
        cfg.max_selloff_pct as u64,
        cfg.max_selloff_period_length,
        0,
        virtual_balance,
        now,
    );
    match probe {
        Ok(Some(r)) => Ok(Some(r.max_selloff_cap.saturating_sub(r.effective_selloff_before))),
        Ok(None) => Ok(None),
        Err(ErrorCode::MaxSelloffExceeded) => Ok(Some(0)),
        Err(e) => Err(e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::coffer::constants::PERCENT_SCALE;
    use solana_pubkey::Pubkey;

    fn two_token_pool(fee_rate: u32, vb: u64, ab: u64) -> CofferPool {
        let mut pool = CofferPool {
            token_count: 2,
            swap_fee_rate: fee_rate,
            protocol_fee_rate: 2_000,
            ..Default::default()
        };
        for (i, slot) in pool.tokens.iter_mut().take(2).enumerate() {
            slot.config.mint = Pubkey::new_from_array([i as u8 + 1; 32]);
            slot.config.normalized_weight = 5_000;
            slot.dynamics.virtual_balance = vb;
            slot.dynamics.actual_balance = ab;
            slot.dynamics.window_start_timestamp = 1_000;
        }
        pool
    }

    #[test]
    fn matches_the_contracts_own_fee_tests() {
        assert_eq!(calculate_swap_fee(3_998, 1_000).unwrap(), 4);
        assert_eq!(calculate_swap_fee(1_000_000, 1_000).unwrap(), 1_000);
        assert_eq!(calculate_swap_fee(1, 1).unwrap(), 1);
        assert_eq!(calculate_protocol_fee(4, 2_000).unwrap(), 1);
        assert_eq!(calculate_protocol_fee(10_000, 2_000).unwrap(), 2_000);
    }

    #[test]
    fn plain_quote_is_fee_then_curve() {
        let pool = two_token_pool(3_000, 1_000_000_000, 1_000_000_000);
        let q = quote_exact_in(&pool, 100_000_000, 0, 1, 9, 9, 1_000).unwrap();
        assert_eq!(q.fee_amount, 300_000);
        assert_eq!(q.protocol_fee_amount, 60_000);
        assert_eq!(q.amount_in_after_fee, 99_700_000);
        let expected = CofferMath::calc_out_given_in(
            1_000_000_000,
            5_000,
            1_000_000_000,
            5_000,
            99_700_000,
            1_000_000_000,
            9,
            9,
        )
        .unwrap();
        assert_eq!(q.amount_out, expected);
        assert_eq!(q.surge_fee_amount, 0);
        assert_eq!(q.amount_out_user, expected);
        assert!(q.max_selloff_result.is_none());
    }

    #[test]
    fn guards_fire_in_handler_order() {
        let mut pool = two_token_pool(3_000, 1_000, 1_000);
        pool.pool_enabled = false;
        assert_eq!(quote_exact_in(&pool, 1, 0, 1, 9, 9, 0).unwrap_err(), ErrorCode::PoolDisabled);
        pool.pool_enabled = true;
        pool.swaps_enabled = false;
        assert_eq!(quote_exact_in(&pool, 1, 0, 1, 9, 9, 0).unwrap_err(), ErrorCode::SwapsDisabled);
        pool.swaps_enabled = true;
        assert_eq!(quote_exact_in(&pool, 0, 0, 1, 9, 9, 0).unwrap_err(), ErrorCode::ZeroAmount);
        assert_eq!(quote_exact_in(&pool, 1, 0, 2, 9, 9, 0).unwrap_err(), ErrorCode::InvalidTokenIndex);
        assert_eq!(quote_exact_in(&pool, 1, 1, 1, 9, 9, 0).unwrap_err(), ErrorCode::InvalidTokenIndex);
        pool.tokens[0].config.is_active = false;
        assert_eq!(quote_exact_in(&pool, 1, 0, 1, 9, 9, 0).unwrap_err(), ErrorCode::TokenInactive);
        // Inactive tokens can still be bought.
        assert!(quote_exact_in(&pool, 100, 1, 0, 9, 9, 0).is_ok());
    }

    #[test]
    fn output_capped_by_actual_balance() {
        let pool = two_token_pool(0, 1_000_000_000, 1_000);
        assert_eq!(
            quote_exact_in(&pool, 100_000_000, 0, 1, 9, 9, 0).unwrap_err(),
            ErrorCode::AmountOutExceedsBalance
        );
        assert!(quote_exact_in(&pool, 1_000, 0, 1, 9, 9, 0).is_ok());
    }

    #[test]
    fn balance_update_overflow_is_a_quote_error_too() {
        let pool = two_token_pool(0, u64::MAX - 10, 1_000);
        // 11 atoms would push the input virtual balance past u64::MAX.
        assert_eq!(quote_exact_in(&pool, 11, 0, 1, 9, 9, 0).unwrap_err(), ErrorCode::MathOverflow);
        assert!(quote_exact_in(&pool, 10, 0, 1, 9, 9, 0).is_ok());
    }

    #[test]
    fn zero_fee_rate_pool_charges_nothing() {
        let pool = two_token_pool(0, 1_000_000_000, 1_000_000_000);
        let q = quote_exact_in(&pool, 7, 0, 1, 9, 9, 0).unwrap();
        assert_eq!(q.fee_amount, 0);
        assert_eq!(q.protocol_fee_amount, 0);
        assert_eq!(q.amount_in_after_fee, 7);
    }

    #[test]
    fn selloff_cap_boundary_is_exact() {
        let mut pool = two_token_pool(3_000, 10_000_000_000, 10_000_000_000);
        pool.tokens[0].config.max_selloff_pct = 1_000; // 10% → cap 1e9
        pool.tokens[0].config.max_selloff_period_length = 60;
        let now = 1_000;
        let headroom = selloff_headroom(&pool, 0, now).unwrap().unwrap();
        assert_eq!(headroom, 1_000_000_000);
        assert!(quote_exact_in(&pool, headroom, 0, 1, 9, 9, now).is_ok());
        assert_eq!(
            quote_exact_in(&pool, headroom + 1, 0, 1, 9, 9, now).unwrap_err(),
            ErrorCode::MaxSelloffExceeded
        );
        // Sell 400M, commit, and the headroom shrinks by exactly that.
        let q = quote_exact_in(&pool, 400_000_000, 0, 1, 9, 9, now).unwrap();
        apply_swap(&mut pool, 0, 1, &q).unwrap();
        assert_eq!(pool.tokens[0].dynamics.current_selloff, 400_000_000);
        assert_eq!(pool.tokens[0].dynamics.selloff_vb_snapshot, 10_000_000_000);
        assert_eq!(selloff_headroom(&pool, 0, now + 5).unwrap().unwrap(), 600_000_000);
        // Two periods later the window is fresh (and re-snapshots the grown vb).
        let h2 = selloff_headroom(&pool, 0, now + 121).unwrap().unwrap();
        assert_eq!(h2, pool.tokens[0].dynamics.virtual_balance / 10);
        assert!(h2 > 1_000_000_000);
    }

    #[test]
    fn surge_fee_kicks_in_above_threshold_and_is_conservative() {
        let mut pool = two_token_pool(3_000, 10_000_000_000, 10_000_000_000);
        let cfg = &mut pool.tokens[0].config;
        cfg.max_selloff_pct = 5_000; // cap 5e9
        cfg.max_selloff_period_length = 3_600;
        cfg.variable_fee_threshold_pct = 8_000; // surge from 80% fill
        cfg.variable_fee_slope_low_pct = 100;
        cfg.variable_fee_slope_mid_pct = 1_000;
        cfg.variable_fee_slope_high_pct = 3_000;
        cfg.variable_fee_kink_pct = 90;
        let now = 1_000;
        // Below the threshold (79% of cap): no surge.
        let q = quote_exact_in(&pool, 3_950_000_000, 0, 1, 9, 9, now).unwrap();
        assert_eq!(q.surge_fee_amount, 0);
        // Full window in one go: taxed span is 80%..100%.
        let q = quote_exact_in(&pool, 5_000_000_000, 0, 1, 9, 9, now).unwrap();
        assert!(q.surge_fee_amount > 0);
        assert_eq!(q.amount_out_user, q.amount_out - q.surge_fee_amount);
        // The fee is bounded by the highest rate applied to the taxed output.
        let taxed_out = q.amount_out
            - CofferMath::calc_out_given_in(
                10_000_000_000,
                5_000,
                10_000_000_000,
                5_000,
                (q.amount_in_after_fee as u128 * 4_000_000_000 / 5_000_000_000) as u64,
                10_000_000_000,
                9,
                9,
            )
            .unwrap();
        assert!(q.surge_fee_amount <= taxed_out * 3_000 / PERCENT_SCALE + 4);
        assert!(q.surge_fee_amount >= taxed_out * 100 / PERCENT_SCALE);
    }
}
